apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 172.16.0.101
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
  name: control1.shabunya.local
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki
clusterName: cluster.local
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
    serverCertSANs:
      - 172.16.0.170
      - control1.shabunya.local
      - control2.shabunya.local
      - control3.shabunya.local
    peerCertSANs:
      - control1.shabunya.local
      - control2.shabunya.local
      - control3.shabunya.local
imageRepository: registry.k8s.io
apiServer: 
  certSANs:
      - 172.16.0.170
      - control1.shabunya.local
      - control2.shabunya.local
      - control3.shabunya.local
  extraArgs:
    - name: authorization-mode
      value: "Node,RBAC"
    - name: bind-address
      value: "0.0.0.0"
    - name: service-cluster-ip-range
      value: "10.96.0.0/18"
    - name: service-node-port-range
      value: "30000-32767"
kubernetesVersion: 1.33.3
controlPlaneEndpoint: 172.16.0.170:7443
networking:
  dnsDomain:      cluster.local
  serviceSubnet:  "10.96.0.0/18"   
  podSubnet:      "10.244.0.0/16"
scheduler: {}
